services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_alura
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_alura:/var/lib/rabbitmq/
    environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root